services:
  - type: web
    name: idotinfra
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /
    envVars:
      - key: WORDPRESS_DB_HOST
        sync: false
      - key: WORDPRESS_DB_NAME
        sync: false
      - key: WORDPRESS_DB_USER
        sync: false
      - key: WORDPRESS_DB_PASSWORD
        sync: false
      - key: WORDPRESS_DB_PORT
        value: "3306"
      - key: WORDPRESS_TABLE_PREFIX
        value: wp_
      - key: WP_ADMIN_USER
        sync: false
      - key: WP_ADMIN_PASSWORD
        sync: false
      - key: WP_ADMIN_EMAIL
        sync: false
